package main

import (
	"io"
	"io/fs"
	"net/http"
	"net/http/httptest"
	"path"
	"regexp"
	"strings"
	"testing"

	"github.com/omegaatt36/dub/app"
	osfs "github.com/omegaatt36/dub/internal/adapter/fs"
	"github.com/omegaatt36/dub/internal/adapter/regex"
	"github.com/omegaatt36/dub/internal/service"
)

// newTestAssetHandler builds the same handler main.go hands to Wails: the
// embedded assets at the root, the application's HTMX API under /api/. Running
// it here is what makes the leak checks below meaningful — they exercise the
// real request chain, not a reimplementation of it.
func newTestAssetHandler(t *testing.T) http.Handler {
	t.Helper()

	fileSystem := &osfs.OSFileSystem{}
	dub := app.NewApp(
		fileSystem,
		service.NewScannerService(fileSystem),
		service.NewPatternService(&regex.Engine{}),
		service.NewRenamerService(fileSystem),
	)

	return newAssetHandler(dub.GetHandler())
}

func get(t *testing.T, handler http.Handler, target string) (int, string) {
	t.Helper()

	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, target, nil))

	body, err := io.ReadAll(rec.Body)
	if err != nil {
		t.Fatalf("read body for %s: %v", target, err)
	}
	return rec.Code, string(body)
}

// goSourceMarkers are substrings that only appear in Go source. A response
// carrying any of them is a source leak, whatever the status code says.
// staticRefPattern pulls the /static/... URLs out of href/src attributes.
var staticRefPattern = regexp.MustCompile(`["'(](/static/[^"')]+)["')]`)

var goSourceMarkers = []string{
	"package template",
	"// Code generated by templ - DO NOT EDIT.",
	"func AppContent(",
	"github.com/a-h/templ",
}

// TestAssetServerDoesNotServeTemplateSources is the security guarantee: the
// templ sources and their generated Go files must not be reachable over HTTP.
func TestAssetServerDoesNotServeTemplateSources(t *testing.T) {
	handler := newTestAssetHandler(t)

	targets := []string{
		"/template/page_templ.go",
		"/template/page.templ",
		"/template/",
		"/template",
		"/web/template/page_templ.go",
	}

	for _, target := range targets {
		t.Run(target, func(t *testing.T) {
			code, body := get(t, handler, target)

			if code == http.StatusOK {
				t.Errorf("GET %s returned 200; the asset FS must not contain web/template", target)
			}
			for _, marker := range goSourceMarkers {
				if strings.Contains(body, marker) {
					t.Errorf("GET %s leaked Go source (found %q)", target, marker)
				}
			}
		})
	}
}

// TestEmbeddedAssetsContainNoTemplateSources proves the guarantee structurally:
// web/template is not in the embedded fs.FS at all, so no request path can
// reach it.
func TestEmbeddedAssetsContainNoTemplateSources(t *testing.T) {
	var leaked []string

	err := fs.WalkDir(assets, ".", func(name string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if strings.HasSuffix(name, ".templ") || strings.HasSuffix(name, "_templ.go") {
			leaked = append(leaked, name)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk embedded assets: %v", err)
	}

	if len(leaked) > 0 {
		t.Errorf("embedded assets contain Go/template sources: %v", leaked)
	}
}

// TestAssetServerServesIndexHTMLAtRoot pins the routing the asset server does on
// its own: "/" must resolve to the embedded web/index.html shell.
func TestAssetServerServesIndexHTMLAtRoot(t *testing.T) {
	handler := newTestAssetHandler(t)

	code, body := get(t, handler, "/")
	if code != http.StatusOK {
		t.Fatalf("GET / = %d, want 200", code)
	}
	if !strings.Contains(body, `<div id="app"`) {
		t.Errorf("GET / did not return the index.html shell, got:\n%s", body)
	}

	// Every asset the shell references has to resolve from the same fs.FS.
	for _, ref := range assetRefsFromIndex(t) {
		t.Run(ref, func(t *testing.T) {
			code, body := get(t, handler, ref)
			if code != http.StatusOK {
				t.Fatalf("GET %s = %d, want 200", ref, code)
			}
			if len(body) == 0 {
				t.Errorf("GET %s served an empty body", ref)
			}
			if strings.Contains(body, "404 page not found") {
				t.Errorf("GET %s served a 404 body with a 200 status", ref)
			}
		})
	}
}

// assetRefsFromIndex reads the shell out of the embedded fs and extracts the
// local /static/... references, so the test follows the HTML instead of a
// hand-kept list.
func assetRefsFromIndex(t *testing.T) []string {
	t.Helper()

	shell, err := assets.ReadFile("web/index.html")
	if err != nil {
		t.Fatalf("read embedded web/index.html: %v", err)
	}

	matches := staticRefPattern.FindAllStringSubmatch(string(shell), -1)
	if len(matches) == 0 {
		t.Fatalf("no /static/ references found in index.html:\n%s", shell)
	}

	refs := make([]string, 0, len(matches))
	for _, m := range matches {
		refs = append(refs, path.Clean(m[1]))
	}
	return refs
}

// TestAssetServerServesEveryEmbeddedStaticFile walks the embedded static tree
// and fetches each file back. It proves the composition (embed web/static, serve
// it under /static/...) reaches everything, including assets the HTML shell does
// not link directly such as the logo the templ components render.
func TestAssetServerServesEveryEmbeddedStaticFile(t *testing.T) {
	handler := newTestAssetHandler(t)

	var served int
	err := fs.WalkDir(assets, "web/static", func(name string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}

		url := "/" + strings.TrimPrefix(name, "web/")
		code, body := get(t, handler, url)
		if code != http.StatusOK {
			t.Errorf("GET %s = %d, want 200", url, code)
			return nil
		}
		want, readErr := assets.ReadFile(name)
		if readErr != nil {
			t.Errorf("read embedded %s: %v", name, readErr)
			return nil
		}
		if body != string(want) {
			t.Errorf("GET %s returned %d bytes, embedded file is %d bytes", url, len(body), len(want))
		}
		served++
		return nil
	})
	if err != nil {
		t.Fatalf("walk embedded static tree: %v", err)
	}
	if served == 0 {
		t.Fatal("no static files were embedded")
	}
	t.Logf("served %d embedded static files", served)
}

// TestAssetServerFallsThroughToAPIHandler confirms the API still wins for its
// own paths, which is what keeps /api/* working now that the FS is rooted at
// web/.
func TestAssetServerFallsThroughToAPIHandler(t *testing.T) {
	handler := newTestAssetHandler(t)

	code, body := get(t, handler, "/api/page")
	if code != http.StatusOK {
		t.Fatalf("GET /api/page = %d, want 200 (the asset FS must fall through to the app handler)", code)
	}
	if !strings.Contains(body, "<") {
		t.Errorf("GET /api/page did not return HTML, got:\n%s", body)
	}
}

// TestAssetServerServesWailsRuntime pins the dependency index.html has on
// /wails/runtime.js: Wails routes a desktop file drop to Go through code that
// lives in that module, so a 404 here silently disables drag & drop.
func TestAssetServerServesWailsRuntime(t *testing.T) {
	handler := newTestAssetHandler(t)

	code, body := get(t, handler, "/wails/runtime.js")
	if code != http.StatusOK {
		t.Fatalf("GET /wails/runtime.js = %d, want 200", code)
	}
	if len(body) == 0 {
		t.Error("GET /wails/runtime.js served an empty body")
	}
}
