// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1070
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/omegaatt36/dub/internal/domain"

type PageData struct {
	SelectedDirectory string
	// VisibleFiles is every file the list renders (pattern-filtered when a
	// pattern is active). Unticked files stay visible so the user can re-tick
	// them instead of hunting for what disappeared.
	VisibleFiles []domain.FileItem
	// ActiveFiles is the ticked subset that a rename applies to. Naming
	// methods and the execute path read this, never VisibleFiles, so a rename
	// can never touch a file the user did not choose.
	ActiveFiles []domain.FileItem
	// SelectedPaths is the ticked set, keyed by absolute path.
	SelectedPaths map[string]bool
	TickedCount   int
	ConflictCount int
	// AllowExtChange reports whether renames may rewrite a file's extension.
	AllowExtChange bool
	// ExtChangeCount is how many previews actually change the extension, which
	// can be fewer than the total even when the policy allows it.
	ExtChangeCount int
	AllFiles       []domain.FileItem
	MatchedFiles   []domain.FileItem
	Pattern        string
	PatternError   string
	NewNames       []string
	Previews       []domain.RenamePreview
	Error          string
	NamingMethod   string
	Template       string
	SearchPattern  string
	ReplacePattern string
	Result         *domain.RenameResult
	CanUndo        bool
}

// AppContent renders the app UI without the HTML shell.
// Used by /api/page — index.html provides the <html>/<head>/<body> shell.
func AppContent(data PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"h-screen flex flex-col\"><!-- Header. Doubles as the window drag handle: the app draws its own\n\t\t     chrome, so the region is marked draggable for Wails. --><div style=\"--wails-draggable: drag;\" class=\"bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 px-4 py-2 flex items-center gap-3 shrink-0\"><img src=\"/static/images/logo.svg\" alt=\"\" class=\"w-7 h-7 shrink-0\"><h1 class=\"text-base font-semibold text-gray-900 dark:text-gray-100 leading-none tracking-tight shrink-0\">Dub</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = DirectorySelector(data.SelectedDirectory).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"ml-auto shrink-0\" style=\"--wails-draggable: no-drag;\"><button id=\"theme-toggle\" type=\"button\" class=\"text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200 p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors focus-visible:ring-2 focus-visible:ring-blue-500\" onclick=\"cycleTheme()\" title=\"Theme: System\" aria-label=\"Theme: System\"><svg data-theme-icon=\"system\" class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M9 17H5a2 2 0 01-2-2V5a2 2 0 012-2h14a2 2 0 012 2v10a2 2 0 01-2 2h-4m-6 0h6m-6 0l-1 3h8l-1-3m5-9v11\"></path></svg> <svg data-theme-icon=\"light\" class=\"w-5 h-5 hidden\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z\"></path></svg> <svg data-theme-icon=\"dark\" class=\"w-5 h-5 hidden\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z\"></path></svg></button></div></div><!-- Main content --><div id=\"main-content\" class=\"flex-1 overflow-hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = MainContent(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func MainContent(data PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ErrorBanner(data.Error).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<!-- The whole body is a drop zone: a file or folder dropped anywhere here\n\t     scans its directory. The names editor nests a narrower zone inside it,\n\t     which closest() resolves first. --><div data-file-drop-target=\"scan\" class=\"h-full flex flex-col min-h-0\"><div class=\"flex-1 min-h-0 grid grid-cols-[minmax(0,3fr)_minmax(0,2fr)] gap-4 p-4 overflow-hidden\"><!-- Left column: file list --><div class=\"flex flex-col min-h-0 overflow-hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = FileList(data.VisibleFiles, data.SelectedPaths, data.Previews, data.Pattern != "", data.TickedCount).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><!-- Right column: filter + naming rules --><div class=\"flex flex-col gap-4 min-h-0 overflow-hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = PatternInput(data.Pattern, len(data.AllFiles), len(data.MatchedFiles), data.PatternError, data.SelectedDirectory != "").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"flex-1 min-h-0 overflow-hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = NamesEditor(EditorData{
			Files:          data.ActiveFiles,
			Names:          data.NewNames,
			Method:         data.NamingMethod,
			Template:       data.Template,
			Search:         data.SearchPattern,
			Replace:        data.ReplacePattern,
			AllowExtChange: data.AllowExtChange,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div></div><!-- Action bar spans the full window so the destructive button sits in a\n\t\t     single consistent place regardless of column heights. -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Actions(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func hasConflicts(previews []domain.RenamePreview) bool {
	for _, p := range previews {
		if p.Conflict {
			return true
		}
	}
	return false
}

var _ = templruntime.GeneratedTemplate
