// Code generated by MockGen. DO NOT EDIT.
// Source: port.go
//
// Generated by this command:
//
//	mockgen -source=port.go -destination=../mock/mock_port.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	os "os"
	reflect "reflect"

	domain "github.com/omegaatt36/dub/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFileSystem is a mock of FileSystem interface.
type MockFileSystem struct {
	ctrl     *gomock.Controller
	recorder *MockFileSystemMockRecorder
	isgomock struct{}
}

// MockFileSystemMockRecorder is the mock recorder for MockFileSystem.
type MockFileSystemMockRecorder struct {
	mock *MockFileSystem
}

// NewMockFileSystem creates a new mock instance.
func NewMockFileSystem(ctrl *gomock.Controller) *MockFileSystem {
	mock := &MockFileSystem{ctrl: ctrl}
	mock.recorder = &MockFileSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileSystem) EXPECT() *MockFileSystemMockRecorder {
	return m.recorder
}

// ReadDir mocks base method.
func (m *MockFileSystem) ReadDir(path string) ([]os.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", path)
	ret0, _ := ret[0].([]os.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockFileSystemMockRecorder) ReadDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockFileSystem)(nil).ReadDir), path)
}

// ReadFile mocks base method.
func (m *MockFileSystem) ReadFile(path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockFileSystemMockRecorder) ReadFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockFileSystem)(nil).ReadFile), path)
}

// Rename mocks base method.
func (m *MockFileSystem) Rename(oldpath, newpath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", oldpath, newpath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockFileSystemMockRecorder) Rename(oldpath, newpath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockFileSystem)(nil).Rename), oldpath, newpath)
}

// Stat mocks base method.
func (m *MockFileSystem) Stat(path string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", path)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockFileSystemMockRecorder) Stat(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockFileSystem)(nil).Stat), path)
}

// MockPatternMatcher is a mock of PatternMatcher interface.
type MockPatternMatcher struct {
	ctrl     *gomock.Controller
	recorder *MockPatternMatcherMockRecorder
	isgomock struct{}
}

// MockPatternMatcherMockRecorder is the mock recorder for MockPatternMatcher.
type MockPatternMatcherMockRecorder struct {
	mock *MockPatternMatcher
}

// NewMockPatternMatcher creates a new mock instance.
func NewMockPatternMatcher(ctrl *gomock.Controller) *MockPatternMatcher {
	mock := &MockPatternMatcher{ctrl: ctrl}
	mock.recorder = &MockPatternMatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatternMatcher) EXPECT() *MockPatternMatcherMockRecorder {
	return m.recorder
}

// ExpandShortcuts mocks base method.
func (m *MockPatternMatcher) ExpandShortcuts(pattern string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpandShortcuts", pattern)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExpandShortcuts indicates an expected call of ExpandShortcuts.
func (mr *MockPatternMatcherMockRecorder) ExpandShortcuts(pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpandShortcuts", reflect.TypeOf((*MockPatternMatcher)(nil).ExpandShortcuts), pattern)
}

// Match mocks base method.
func (m *MockPatternMatcher) Match(pattern, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", pattern, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Match indicates an expected call of Match.
func (mr *MockPatternMatcherMockRecorder) Match(pattern, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockPatternMatcher)(nil).Match), pattern, name)
}

// MockScanner is a mock of Scanner interface.
type MockScanner struct {
	ctrl     *gomock.Controller
	recorder *MockScannerMockRecorder
	isgomock struct{}
}

// MockScannerMockRecorder is the mock recorder for MockScanner.
type MockScannerMockRecorder struct {
	mock *MockScanner
}

// NewMockScanner creates a new mock instance.
func NewMockScanner(ctrl *gomock.Controller) *MockScanner {
	mock := &MockScanner{ctrl: ctrl}
	mock.recorder = &MockScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanner) EXPECT() *MockScannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockScanner) Scan(path string) ([]domain.FileItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", path)
	ret0, _ := ret[0].([]domain.FileItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockScannerMockRecorder) Scan(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockScanner)(nil).Scan), path)
}

// MockPatternFilter is a mock of PatternFilter interface.
type MockPatternFilter struct {
	ctrl     *gomock.Controller
	recorder *MockPatternFilterMockRecorder
	isgomock struct{}
}

// MockPatternFilterMockRecorder is the mock recorder for MockPatternFilter.
type MockPatternFilterMockRecorder struct {
	mock *MockPatternFilter
}

// NewMockPatternFilter creates a new mock instance.
func NewMockPatternFilter(ctrl *gomock.Controller) *MockPatternFilter {
	mock := &MockPatternFilter{ctrl: ctrl}
	mock.recorder = &MockPatternFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatternFilter) EXPECT() *MockPatternFilterMockRecorder {
	return m.recorder
}

// MatchFiles mocks base method.
func (m *MockPatternFilter) MatchFiles(files []domain.FileItem, pattern string) ([]domain.FileItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchFiles", files, pattern)
	ret0, _ := ret[0].([]domain.FileItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchFiles indicates an expected call of MatchFiles.
func (mr *MockPatternFilterMockRecorder) MatchFiles(files, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchFiles", reflect.TypeOf((*MockPatternFilter)(nil).MatchFiles), files, pattern)
}

// MockRenamer is a mock of Renamer interface.
type MockRenamer struct {
	ctrl     *gomock.Controller
	recorder *MockRenamerMockRecorder
	isgomock struct{}
}

// MockRenamerMockRecorder is the mock recorder for MockRenamer.
type MockRenamerMockRecorder struct {
	mock *MockRenamer
}

// NewMockRenamer creates a new mock instance.
func NewMockRenamer(ctrl *gomock.Controller) *MockRenamer {
	mock := &MockRenamer{ctrl: ctrl}
	mock.recorder = &MockRenamerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRenamer) EXPECT() *MockRenamerMockRecorder {
	return m.recorder
}

// ExecuteRename mocks base method.
func (m *MockRenamer) ExecuteRename(previews []domain.RenamePreview) domain.RenameResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteRename", previews)
	ret0, _ := ret[0].(domain.RenameResult)
	return ret0
}

// ExecuteRename indicates an expected call of ExecuteRename.
func (mr *MockRenamerMockRecorder) ExecuteRename(previews any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteRename", reflect.TypeOf((*MockRenamer)(nil).ExecuteRename), previews)
}

// PreviewRename mocks base method.
func (m *MockRenamer) PreviewRename(files []domain.FileItem, newNames []string) ([]domain.RenamePreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewRename", files, newNames)
	ret0, _ := ret[0].([]domain.RenamePreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewRename indicates an expected call of PreviewRename.
func (mr *MockRenamerMockRecorder) PreviewRename(files, newNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewRename", reflect.TypeOf((*MockRenamer)(nil).PreviewRename), files, newNames)
}
